# Generated by Django 6.1 on 2026-08-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NUMBERS', 'Números'), ('CARDS', 'Cartas'), ('WORDS', 'Palavras'), ('SPOKEN_NUMBERS', 'Números falados'), ('NAMES_AND_FACES', 'Nomes e rostos'), ('ABSTRACT_IMAGES', 'Imagens abstratas')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_memo', to='trainer.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_memo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
