# Generated by Django 6.1 on 2026-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_discipline_sessionmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmemory',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionmemory',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sessionmemory',
            name='errors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionmemory',
            name='memo_selected_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionmemory',
            name='memo_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionmemory',
            name='recall_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionmemory',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
